[2023-01-29T15:29:11.503+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crawl_tienphong.save-to-hdfs manual__2023-01-29T15:28:49.320466+00:00 [queued]>
[2023-01-29T15:29:11.513+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: crawl_tienphong.save-to-hdfs manual__2023-01-29T15:28:49.320466+00:00 [queued]>
[2023-01-29T15:29:11.513+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T15:29:11.513+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-01-29T15:29:11.513+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T15:29:11.531+0000] {taskinstance.py:1300} INFO - Executing <Task(SSHOperator): save-to-hdfs> on 2023-01-29 15:28:49.320466+00:00
[2023-01-29T15:29:11.536+0000] {standard_task_runner.py:55} INFO - Started process 11208 to run task
[2023-01-29T15:29:11.538+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crawl_tienphong', 'save-to-hdfs', 'manual__2023-01-29T15:28:49.320466+00:00', '--job-id', '1411', '--raw', '--subdir', 'DAGS_FOLDER/crawl_tienphong.py', '--cfg-path', '/tmp/tmp_ue3fkk0']
[2023-01-29T15:29:11.539+0000] {standard_task_runner.py:83} INFO - Job 1411: Subtask save-to-hdfs
[2023-01-29T15:29:11.599+0000] {task_command.py:388} INFO - Running <TaskInstance: crawl_tienphong.save-to-hdfs manual__2023-01-29T15:28:49.320466+00:00 [running]> on host 9be4ecca8506
[2023-01-29T15:29:11.680+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=phukaioh
AIRFLOW_CTX_DAG_ID=crawl_tienphong
AIRFLOW_CTX_TASK_ID=save-to-hdfs
AIRFLOW_CTX_EXECUTION_DATE=2023-01-29T15:28:49.320466+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-29T15:28:49.320466+00:00
[2023-01-29T15:29:11.680+0000] {ssh.py:133} INFO - Creating ssh_client
[2023-01-29T15:29:11.681+0000] {ssh.py:283} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-01-29T15:29:11.688+0000] {transport.py:1874} INFO - Connected (version 2.0, client OpenSSH_8.2p1)
[2023-01-29T15:29:11.749+0000] {transport.py:1874} INFO - Authentication (password) successful!
[2023-01-29T15:29:11.750+0000] {ssh.py:460} INFO - Running command: hdfs dfs -copyFromLocal -f /home/phukaioh/Documents/intro-data-science/crawler/data/tienphong.json /data/tienphong-29-01-2023.json 
[2023-01-29T15:29:11.882+0000] {ssh.py:501} WARNING - bash: hdfs: command not found
[2023-01-29T15:29:11.905+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 171, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 159, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/operators/ssh.py", line 152, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 127
[2023-01-29T15:29:11.909+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=crawl_tienphong, task_id=save-to-hdfs, execution_date=20230129T152849, start_date=20230129T152911, end_date=20230129T152911
[2023-01-29T15:29:11.919+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1411 for task save-to-hdfs (SSH operator error: exit status = 127; 11208)
[2023-01-29T15:29:11.960+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-29T15:29:11.979+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
